### PR TITLE
Resync locations with documented allowed locations

### PR DESCRIPTION
**Pull request by johndowns**
This PR updates the action's parameter validation to resync the allowed location list with the [list in the product documentation](https://learn.microsoft.com/azure/virtual-machines/image-builder-overview?tabs=azure-powershell#regions).

### CODE REVIEW

**Comment by johndowns** [comment]
Hi @BALAGA-GAYATRI, are you able to help to get this PR merged, please?

**Comment by briansaxbergMSFT** [comment]
Greetings team, @BALAGA-GAYATRI could I get an ETA on when this might be merged?  I have a customer who is trying to make this work with GitHub Actions and Azure Image Builder.  Thank you and @johndowns!

**Comment by briansaxbergMSFT** [comment]
Thank you!

**Comment by BALAGA-GAYATRI** [comment]
Hi, released the changes https://github.com/Azure/build-vm-image/releases/tag/v0.1.1

**Comment by RPagels** [comment]
@BALAGA-GAYATRI or @johndowns , do either of know why this GH Action isn't building for any other Azure location, but "**eastus2**"? (Same customer that @briansaxbergMSFT is working with)

**Comment by johndowns** [comment]
@RPagels Could you provide a snippet of the GitHub workflow YAML to illustrate this please?

**Comment by RPagels** [comment]
@johndowns , here you go.
 
The customer tried a couple things
•	azure/build-vm-image@v0.1.1
•	azure/build-vm-image@v0.1.
•	azure/build-vm-image@v0.1

image

image

**Comment by johndowns** [comment]
@RPagels Unfortunately the change we made in this PR wasn't sufficient to fix the issue, because the compiled JavaScript files are in the repo and need to be updated as well. I've opened another PR to fix this (hopefully properly this time!): #24

**Comment by RPagels** [comment]
@johndowns , thank you for the update.  I'll wait to see when #24 is merged and have customer test it out.

**Pull request merged**
