### PR TITLE
Resync locations with documented allowed locations (JavaScript update)

### PR DESCRIPTION
**Pull request by johndowns**
This is a follow-up to #20. It looks like updating the TypeScript file isn't sufficient, and the JavaScript file also needs to be updated. This PR makes the same change to the JavaScript file.

### CODE REVIEW

**Comment by johndowns** [comment]
@BALAGA-GAYATRI Could you please review this PR? Thanks.

**Comment by BALAGA-GAYATRI** [comment]
@johndowns Please raise the PR for necessary changes for `releases/v0` branch as well? Thanks!

**Comment by briansaxbergMSFT** [comment]
@johndowns  and @BALAGA-GAYATRI  Thank you both so much!  I am confirming if I should have the customer try this again?

**Comment by johndowns** [comment]
@BALAGA-GAYATRI I'm afraid I don't understand what you're asking me to do here - I'm not familiar with your release process. Do you want me to open a PR from this branch on my fork to the release/v0 branch?

**Comment by johndowns** [comment]
@BALAGA-GAYATRI While we're talking about release processes - would it make sense for your build process to generate the JS file from the TS file, so you don't end up with them out of sync again?

**Pull request merged**
